dist: bionic
os: linux
language: python

jobs:
  include:
    - name: "MTGJSON4 Code Analysis Python36"
      before_install:
        - cd "mtgjson4"
        - "pip install -U pip setuptools wheel tox-travis"
      install: "pip install -r requirements.txt -r requirements_test.txt"
      script: tox
      python: "3.6"

    - name: "MTGJSON4 Code Analysis Python37"
      before_install:
        - cd "mtgjson4"
        - "pip install -U pip setuptools wheel tox-travis"
      install: "pip install -r requirements.txt -r requirements_test.txt"
      script: tox
      python: "3.7"

    - name: "MTGJSON5 Code Analysis Python36"
      before_install:
        - cd "mtgjson5"
        - "pip install -U pip setuptools wheel tox-travis"
      install: "pip install -r requirements.txt -r requirements_test.txt"
      script: tox
      python: "3.6"

    - name: "MTGJSON5 Code Analysis Python37"
      before_install:
        - cd "mtgjson5"
        - "pip install -U pip setuptools wheel tox-travis"
      install: "pip install -r requirements.txt -r requirements_test.txt"
      script: tox
      python: "3.7"